WebApplication1/Pages/Cart/Checkout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication1.DataAccess;

namespace WebApplication1.Pages.Cart
{
    public class CheckoutModel : PageModel
    {
        public void OnGet()
        {
            String jsonCart = HttpContext.Session.GetString("jsonCart");

            CartDetail c = new CartDetail();
            if (jsonCart != null)
            {
                c = Newtonsoft.Json.JsonConvert.DeserializeObject<CartDetail>(jsonCart);
            }
        }
    }
}

WebApplication1/Pages/Cart/Items.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication1.DataAccess;

namespace WebApplication1.Pages.Cart
{
    public class ItemsModel : PageModel
    {
        public void OnGet()
        {
            String jsonCart = HttpContext.Session.GetString("jsonCart");

            CartDetail c = new CartDetail();
            if (jsonCart != null)
            {
                c = Newtonsoft.Json.JsonConvert.DeserializeObject<CartDetail>(jsonCart);
            }

            ViewData["cart"] = c;
        }

        public void OnPostDelete(int Id)
        {
            String jsonCart = HttpContext.Session.GetString("jsonCart");

            CartDetail c = new CartDetail();
            if (jsonCart != null)
            {
                c = Newtonsoft.Json.JsonConvert.DeserializeObject<CartDetail>(jsonCart);
                c.removeItem(Id);

                c.Total = c.getTotalMoney();
            }

            ViewData["cart"] = c;
            jsonCart = Newtonsoft.Json.JsonConvert.SerializeObject(c);
            HttpContext.Session.SetString("jsonCart", jsonCart);
        }

        public void OnPostChangeQuantity(int Id, int amount)
        {
            String jsonCart = HttpContext.Session.GetString("jsonCart");

            CartDetail c = new CartDetail();
            if (jsonCart != null)
            {
                c = Newtonsoft.Json.JsonConvert.DeserializeObject<CartDetail>(jsonCart);
                c.getExactItem(Id).Quantity = amount;

                c.Total = c.getTotalMoney();
            }

            ViewData["cart"] = c;
            jsonCart = Newtonsoft.Json.JsonConvert.SerializeObject(c);
            HttpContext.Session.SetString("jsonCart", jsonCart);
        }
    }
}

WebApplication1/Pages/Cart/Checkout.cshtml
@page
@model WebApplication1.Pages.Cart.CheckoutModel
@{
}

WebApplication1/Pages/Cart/Items.cshtml
@page
@model WebApplication1.Pages.Cart.ItemsModel
@using WebApplication1.DataAccess
@{
    Layout = "_Layout";
}

@{
    var cart = (CartDetail)ViewData["cart"];
}

<section class="pt-5 pb-5">
  <div class="container">
    <div class="row w-100">
        <div class="col-lg-12 col-md-12 col-12">
            <h3 class="display-5 mb-2 text-center">Shopping Cart</h3>
            <p class="mb-5 text-center">
                <i class="text-info font-weight-bold">@cart.Items.Count</i> items in your cart</p>
            <table id="shoppingCart" class="table table-condensed table-responsive">
                <thead>
                    <tr>
                        <th style="width:60%">Product</th>
                        <th style="width:12%">Price</th>
                        <th style="width:10%">Quantity</th>
                        <th style="width:10%">Subtotal</th>
                        <th style="width:16%"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(var item in cart.Items){
                        <tr>
                            <td data-th="Product">
                                <div class="row">
                                    <div class="col-md-3 text-left">
                                        <img src="https://via.placeholder.com/250x250/5fa9f8/ffffff" alt="" class="img-fluid d-none d-md-block rounded mb-2 shadow ">
                                    </div>
                                    <div class="col-md-9 text-left mt-sm-2">
                                        <h4>@item.Product.ProductName</h4>
                                        <p class="font-weight-light">@item.Product.QuantityPerUnit</p>
                                    </div>
                                </div>
                            </td>
                            <td data-th="Price">$@item.Product.UnitPrice</td>
                            <td data-th="Quantity">
                                <form method="post" asp-page-handler="ChangeQuantity">
                                    <input type="text" name="Id" value="@item.Id" hidden/>
                                    <input type="number" min="1" onchange="this.form.submit()" name="amount" class="form-control form-control-lg text-center" value="@item.Quantity">
                                </form>
                            </td>
                            <td data-th="Price">$@(item.Product.UnitPrice*item.Quantity)</td>
                            <td class="actions" data-th="">
                                <form method="post" asp-page-handler="Delete">
                                    <input type="text" name="Id" value="@item.Id" hidden/>
                                    <div class="text-right"> 
                                        <input type="submit" class="btn btn-danger border-secondary btn-md mb-2" value="Remove"/>
                                    </div>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="float-right text-right">
                <h4>Total:</h4>
                <h1>$@cart.Total</h1>
            </div>
        </div>
    </div>
    <div class="row mt-4 d-flex align-items-center">
        <div class="col-sm-6 order-md-2 text-right">
            <a href="/Cart/Checkout" class="btn btn-primary mb-4 btn-lg pl-5 pr-5">Checkout</a>
        </div>
        <div class="col-sm-6 mb-3 mb-m-1 order-md-1 text-md-left">
            <a class="nav-link text-dark" asp-area="" asp-page="/Products/List">
                <i class="fas fa-arrow-left mr-2"></i> Continue Shopping</a>
        </div>
    </div>
</div>
</section>