WebApplication1/Pages/Admin/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication1.Pages.Admin
{
    public class ListModel : PageModel
    {
        [BindProperty (SupportsGet = true)]
        public int Id { get; set; }
        [BindProperty(SupportsGet = true)]
        public string Name { get; set; }

        public void OnGet(int Id, string Name)
        {
            ViewData["id"] = Id;
            ViewData["name"] = Name;
        }

        public void OnPost()
        {

        }
    }
}

WebApplication1/Pages/Orders/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApplication1.DataAccess;

namespace WebApplication1.Pages.Orders
{
    public class ListModel : PageModel
    {
        private NorthwindContext context = new NorthwindContext();

        public void OnGet(int Id)
        {
            List<Employee> employees;

            if (Id == 0)
            {
                employees = context.Employees.Include(x => x.Orders).Take(30).ToList();
            }
            else
            {
                employees = context.Employees.Where(e => e.EmployeeId == Id).Include(x => x.Orders).Take(30).ToList();
            }

            ViewData["employees"] = employees;
        }
    }
}

WebApplication1/Pages/Products/Add.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using WebApplication1.DataAccess;

namespace WebApplication1.Pages.Products
{
    public class AddModel : PageModel
    {
        NorthwindContext context = new NorthwindContext();

        public void OnGet()
        {
            List<Supplier> suppliers = context.Suppliers.ToList();
            List<Category> categories = context.Categories.ToList();

            ViewData["suppliers"] = suppliers;
            ViewData["categories"] = categories;
        }

        public IActionResult OnPost(Product product)
        {
            context.Products.Add(product);
            context.SaveChanges();

            return Redirect("/Products/List");
        }
    }
}

WebApplication1/Pages/Products/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication1.DataAccess;

namespace WebApplication1.Pages.Products
{
    public class DeleteModel : PageModel
    {
        NorthwindContext context = new NorthwindContext();

        public IActionResult OnGet(int Id)
        {
            Product product = context.Products.FirstOrDefault(p => p.ProductId == Id);

            context.Products.Remove(product);
            context.SaveChanges();

            return Redirect("/Products/List");
        }
    }
}

WebApplication1/Pages/Products/Detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApplication1.DataAccess;
using System.Text.Json;
using Newtonsoft.Json;

namespace WebApplication1.Pages.Products
{
    public class DetailModel : PageModel
    {
        NorthwindContext context = new NorthwindContext();

        public void OnGet(int productId)
        {
            Product p = context.Products.Include(p => p.Category).Include(p => p.Supplier).FirstOrDefault(p => p.ProductId == productId);

            ViewData["product"] = p;
        }

        public IActionResult OnPostCart(int productId, int num)
        {
            Product p = context.Products.FirstOrDefault(p => p.ProductId == productId);

            ItemInCart i = new ItemInCart();
            i.Quantity = num;
            i.Product = p;

            CartDetail c = new CartDetail();
            String jsonCart = HttpContext.Session.GetString("jsonCart");
            if (jsonCart != null)
            {
                c = Newtonsoft.Json.JsonConvert.DeserializeObject<CartDetail>(jsonCart);
            }

            i.Id = c.Items.Count + 1;

            c.addItem(i);
            c.Total = c.getTotalMoney();

            jsonCart = Newtonsoft.Json.JsonConvert.SerializeObject(c);
            HttpContext.Session.SetString("jsonCart", jsonCart);

            return Redirect("/Cart/Items");
        }
    }
}

WebApplication1/Pages/Products/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication1.DataAccess;

namespace WebApplication1.Pages.Products
{
    public class EditModel : PageModel
    {
        NorthwindContext context = new NorthwindContext();

        public void OnGet(int Id)
        {
            List<Supplier> suppliers = context.Suppliers.ToList();
            List<Category> categories = context.Categories.ToList();
            Product product = context.Products.FirstOrDefault(p => p.ProductId == Id);

            ViewData["product"] = product;
            ViewData["suppliers"] = suppliers;
            ViewData["categories"] = categories;
        }

        public IActionResult OnPost(Product product)
        {
            context.Products.Update(product);
            context.SaveChanges();

            return Redirect("/Products/List");
        }
    }
}

WebApplication1/Pages/Products/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Collections;
using System.Drawing;
using WebApplication1.DataAccess;

namespace WebApplication1.Pages.Products
{
    public class ListModel : PageModel
    {
        NorthwindContext context = new NorthwindContext();

        List<Product> classProducts;

        public void OnGet(int pageNumber)
        {
            List<Boolean> selected = new List<Boolean>();
            int pageSize = 10;
            if (pageNumber <= 0) pageNumber = 1;
            int offSet = (pageNumber - 1) * pageSize + 1;

            //List<Product> products = context.Products.Include(p => p.Supplier).Include(p => p.Category).ToList();
            List<Product> products = context.Products.Skip(offSet - 1).Include(p => p.Supplier).Include(p => p.Category).Take(pageSize).ToList();
            List<Category> categories = context.Categories.ToList();

            for (int i = 1; i <= categories.Count; i++)
            {
                selected.Add(false);
            }

            ////lay cac thong tin de hien thi thanh Pager
            int TotalProduct = context.Products.ToList().Count;
            int TotalPage = (TotalProduct / pageSize);
            if (TotalProduct % pageSize != 0) TotalPage++;
            ViewData["TotalPage"] = TotalPage;
            ViewData["CurrentPage"] = pageNumber;

            // lay products va data de hien thi len View
            ViewData["priceFrom"] = "";
            ViewData["priceTo"] = "";
            ViewData["products"] = products;
            ViewData["categories"] = categories;
            ViewData["selectCate"] = selected;
        }

        public void OnPostFilter(List<int> category, string searchName, decimal priceFrom, decimal priceTo)
        {
            List<Product> products;
            List<Boolean> selected = new List<Boolean>();
            List<Category> categories = context.Categories.ToList();

            if (category.Count > 0)
            {
                products = new List<Product>();

                foreach (var categoryId in category)
                {
                    List<Product> p = context.Products.Where(p => p.CategoryId == categoryId).Include(p => p.Supplier).Include(p => p.Category).ToList();
                    products = products.Concat(p).OrderBy(p => p.ProductId).ToList();
                }


                for(int i=1; i<=categories.Count; i++)
                {
                    if (category.Contains(i)) selected.Add(true);
                    else selected.Add(false);
                }
            }
            else
            {
                products = context.Products.Include(p => p.Supplier).Include(p => p.Category).ToList();
                for (int i = 1; i <= categories.Count; i++)
                {
                    selected.Add(false);
                }
            }

            if (searchName != "" && searchName != null)
            {
                products = products.Where(p => p.ProductName.Contains(searchName)).ToList();
            }

            if (priceFrom != 0)
            {
                products = products.Where(p => p.UnitPrice >= priceFrom).ToList();
            }

            if (priceTo != 0)
            {
                products = products.Where(p => p.UnitPrice <= priceTo).ToList();
            }

            int pageSize = 10;
            int pageNumber = 1;
            int offSet = (pageNumber - 1) * pageSize + 1;

            
            int TotalProduct = products.Count;
            int TotalPage = (TotalProduct / pageSize);
            if (TotalProduct % pageSize != 0) TotalPage++;
            ViewData["TotalPage"] = TotalPage;
            ViewData["CurrentPage"] = pageNumber;

            ViewData["priceFrom"] = priceFrom == 0 ? "" : priceFrom.ToString();
            ViewData["priceTo"] = priceTo == 0 ? "" : priceTo.ToString();
            ViewData["searchName"] = searchName;
            ViewData["products"] = products.Skip(offSet - 1).Take(pageSize).ToList();
            ViewData["categories"] = categories;
            ViewData["selectCate"] = selected;
        }

        public void OnPostPaging(List<int> category, string searchName, decimal priceFrom, decimal priceTo, int pageNumber)
        {
            List<Product> products;
            List<Boolean> selected = new List<Boolean>();
            List<Category> categories = context.Categories.ToList();

            if (category.Count > 0)
            {
                products = new List<Product>();

                foreach (var categoryId in category)
                {
                    List<Product> p = context.Products.Where(p => p.CategoryId == categoryId).Include(p => p.Supplier).Include(p => p.Category).ToList();
                    products = products.Concat(p).OrderBy(p => p.ProductId).ToList();
                }


                for (int i = 1; i <= categories.Count; i++)
                {
                    if (category.Contains(i)) selected.Add(true);
                    else selected.Add(false);
                }
            }
            else
            {
                products = context.Products.Include(p => p.Supplier).Include(p => p.Category).ToList();
                for (int i = 1; i <= categories.Count; i++)
                {
                    selected.Add(false);
                }
            }

            if (searchName != "" && searchName != null)
            {
                products = products.Where(p => p.ProductName.Contains(searchName)).ToList();
            }

            if (priceFrom != 0)
            {
                products = products.Where(p => p.UnitPrice >= priceFrom).ToList();
            }

            if (priceTo != 0)
            {
                products = products.Where(p => p.UnitPrice <= priceTo).ToList();
            }

            int pageSize = 10;
            if (pageNumber <= 0) pageNumber = 1;
            int offSet = (pageNumber - 1) * pageSize + 1;


            int TotalProduct = products.Count;
            int TotalPage = (TotalProduct / pageSize);
            if (TotalProduct % pageSize != 0) TotalPage++;
            ViewData["TotalPage"] = TotalPage;
            ViewData["CurrentPage"] = pageNumber;

            products = products.Skip(offSet - 1).Take(pageSize).ToList();

            ViewData["priceFrom"] = priceFrom == 0 ? "" : priceFrom.ToString();
            ViewData["priceTo"] = priceTo == 0 ? "" : priceTo.ToString();
            ViewData["searchName"] = searchName;
            ViewData["products"] = products;
            ViewData["categories"] = categories;
            ViewData["selectCate"] = selected;
        }
    }
}

WebApplication1/Pages/Products/Add.cshtml
@page
@model WebApplication1.Pages.Products.AddModel
@using WebApplication1.DataAccess
@{
    Layout = "_Layout";
}

@{
    var suppliers = (List<Supplier>)ViewData["suppliers"];
    var categories = (List<Category>)ViewData["categories"];
}

<div>
    <form method="post" class="m-2 p-3 bg-light">
      <div class="form-group m-2">
          <label for="product.productName">Product Name</label>
          <input type="text" name="product.productName" />
      </div>
      <div class="form-group m-2">
          <label for="product.supplierID">Supplier</label>
          <select name="product.supplierID">
            @foreach(var s in suppliers){
                <option value="@s.SupplierId">@s.CompanyName</option>
            }
          </select>
      </div>
      <div class="form-group m-2">
          <label for="product.categoryID">Category</label>
          <select name="product.categoryID">
                @foreach (var c in categories)
                {
                    <option value="@c.CategoryId">@c.CategoryName</option>
                }
          </select>
      </div>
      <div class="form-group m-2">
          <label for="product.quantityPerUnit">Quantity Per Unit</label>
          <input type="text" name="product.quantityPerUnit" />
      </div>
      <div class="form-group m-2">
          <label for="product.unitPrice">Unit Price</label>
          <input type="text" name="product.unitPrice" />
      </div>
      <div class="form-group m-2">
          <label for="product.unitsInStock">Unit In Stock</label>
          <input type="number" name="product.unitsInStock" value=0 />
      </div>
      <div class="form-group m-2">
          <label for="product.discontinued">Discontinued</label>
          <input type="radio" name="product.discontinued" value=true />Yes
          <input type="radio" name="product.discontinued" value=false checked/>No
      </div>
      <div class="form-group m-2">
          <input class="btn btn-danger" type="submit" value="Add Product" />
      </div>
    </form>
</div>

WebApplication1/Pages/Products/Delete.cshtml
@page
@model WebApplication1.Pages.Products.DeleteModel
@{
}

WebApplication1/Pages/Products/Detail.cshtml
@page
@model WebApplication1.Pages.Products.DetailModel
@using WebApplication1.DataAccess
@{
    Layout = "_Layout";
}

@{
    var product = (Product)ViewData["product"];
}




<div class="container">
    <div class="col-lg-8 border p-3 main-section bg-white">
        <div class="row m-0">
            <div class="col-lg-4 left-side-product-box pb-3">
                <img src="http://nicesnippets.com/demo/pd-image1.jpg" class="border p-3">
            </div>
            <div class="col-lg-8">
                <div class="right-side-pro-detail border p-3 m-0">
                    <div class="row">
                        <form method="post" asp-page-handler="Cart">
                            <div class="col-lg-12">
                                <span>@product.ProductId</span>
                                <input type="text" name="productId" value="@product.ProductId" hidden/>
                                <p class="m-0 p-0">@product.ProductName</p>
                            </div>
                            <div class="col-lg-12">
                                <p class="m-0 p-0 price-pro">$@product.UnitPrice</p>
                                <hr class="p-0 m-0">
                            </div>
                            <div class="col-lg-12 pt-2">
                                <h5>Product Detail</h5>
                                <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                                    quis nostrud exercitation ullamco laboris.</span>
                                <hr class="m-0 pt-2 mt-2">
                            </div>
                            <div class="col-lg-12">
                                <p class="tag-section"><strong>Category : </strong> @product.Category.CategoryName</p>
                            </div>
                            <div class="col-lg-12">
                                <h6>Quantity :</h6>
                                <input type="number" name="num" class="form-control text-center w-100" min="1" max="@product.UnitsInStock" value="1">
                            </div>
                            <div class="col-lg-12 mt-3">
                                <div class="row">
                                    <div class="col-lg-6 pb-2">
                                        <input type="submit" value="Add To Cart" />
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<style>

    .main-section {
        position: absolute;
        left: 50%;
        right: 50%;
        transform: translate(-50%, 5%);
    }

    .left-side-product-box img {
        width: 100%;
    }

    .left-side-product-box .sub-img img {
        margin-top: 5px;
        width: 83px;
        height: 100px;
    }

    .right-side-pro-detail span {
        font-size: 15px;
    }

    .right-side-pro-detail p {
        font-size: 25px;
        color: #a1a1a1;
    }

    .right-side-pro-detail .price-pro {
        color: #E45641;
    }

    .right-side-pro-detail .tag-section {
        font-size: 18px;
        color: #5D4C46;
    }

    .pro-box-section .pro-box img {
        width: 100%;
        height: 200px;
    }
</style>

WebApplication1/Pages/Products/Edit.cshtml
@page "{Id=}"
@model WebApplication1.Pages.Products.EditModel
@using WebApplication1.DataAccess
@{
}

@{
    var product = (Product)ViewData["product"];
    var suppliers = (List<Supplier>)ViewData["suppliers"];
    var categories = (List<Category>)ViewData["categories"];
}

<div>
    <form method="post" class="m-2 p-3 bg-light">
      <div class="form-group m-2" hidden>
          <label for="product.productName">Product Name</label>
          <input type="text" name="product.productId" value="@product.ProductId"/>
      </div>
      <div class="form-group m-2">
          <label for="product.productName">Product Name</label>
          <input type="text" name="product.productName" value="@product.ProductName"/>
      </div>
      <div class="form-group m-2">
          <label for="product.supplierID">Supplier</label>
          <select name="product.supplierID">
                @foreach (var s in suppliers)
                {
                    <!option value="@s.SupplierId" @(s.SupplierId == product.SupplierId ? "selected" : "")>@s.CompanyName</!option>
                }
          </select>
      </div>
      <div class="form-group m-2">
          <label for="product.categoryID">Category</label>
          <select name="product.categoryID">
                @foreach (var c in categories)
                {
                    <!option value="@c.CategoryId" @(c.CategoryId == product.CategoryId ? "selected" : "")>@c.CategoryName</!option>
                }
          </select>
      </div>
      <div class="form-group m-2">
          <label for="product.quantityPerUnit">Quantity Per Unit</label>
          <input type="text" name="product.quantityPerUnit" value="@product.QuantityPerUnit"/>
      </div>
      <div class="form-group m-2">
          <label for="product.unitPrice">Unit Price</label>
          <input type="text" name="product.unitPrice" value="@product.UnitPrice"/>
      </div>
      <div class="form-group m-2">
          <label for="product.unitsInStock">Unit In Stock</label>
          <input type="number" name="product.unitsInStock" value=@product.UnitsInStock />
      </div>
      <div class="form-group m-2">
          <label for="product.discontinued">Discontinued</label>
          <input type="radio" name="product.discontinued" value=true @(product.Discontinued ? "checked" : "")/>Yes
          <input type="radio" name="product.discontinued" value=false @(product.Discontinued ? "" : "checked")/>No
      </div>
      <div class="form-group m-2">
          <input class="btn btn-info" type="submit" value="Update Product" />
      </div>
    </form>
</div>

WebApplication1/Pages/Products/List.cshtml
@page "{PageNumber=0}"

@model WebApplication1.Pages.Products.ListModel
@using WebApplication1.DataAccess
@addTagHelper *, WebApplication1
@{
    Layout = "_Layout";
}

@{
    var products = (List<Product>) ViewData["products"];
    var categories = (List<Category>)ViewData["categories"];
    var selectCate = (List<Boolean>)ViewData["selectCate"];

    var priceFrom = (String)ViewData["priceFrom"];
    var priceTo = (String)ViewData["priceTo"];

    var query = "";
    if ((String) ViewData["searchName"] != null){
        query = (String)ViewData["searchName"];
    }
}

<style>
    .active{
        font-size: large;
        font-weight: bold;
        color: darkblue;
    }
</style>

<div class="row">
    <div class="filter-container col-2">
        <form method="post" asp-page-handler="filter">
            <div class="form-group m-2">
                <label for="categoryId">Filter</label>
                @foreach (var c in categories)
                {
                        <br/>
                            <input type="checkbox" name="category" value="@c.CategoryId" @(selectCate[categories.IndexOf(c)] ? "checked" : "")/>@c.CategoryName
                }
            </div>
            <div class="form-group m-2">
                <label for="searchName">Search</label>
                <input type="text" name="searchName" placeholder="Product Name" value="@query"/><br/>
            </div>
            <div class="form-group m-2">
                <label for="searchName">Price</label>
                <input class="w-40" type="text" name="priceFrom" placeholder="From" value="@priceFrom" />
                <input class="w-40" type="text" name="priceTo" placeholder="To" value="@priceTo" />
            </div>
            <input class="btn btn-primary" type="submit" value="Filter" />
        </form>
    </div>
    <div class="col-10">
        <a asp-area="" asp-page="/Products/Add">Add Product</a>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Category</th>
                    <th>Supplier</th>
                    <th>Unit Price</th>
                    <th>Discontinued</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach(var p in products){
                    <tr>
                        <td>@p.ProductId</td>
                        <td><a asp-area="" asp-page="/Products/Detail" asp-route-productId="@p.ProductId">@p.ProductName</a></td>
                        <td>@p.Category.CategoryName</td>
                        <td>@p.Supplier.CompanyName</td>
                        <td>@p.UnitPrice</td>
                        <td>@p.Discontinued</td>
                        <td><a asp-area="" asp-page="/Products/Edit" asp-route-id="@p.ProductId">Edit</a></td>
                        <td><a asp-area="" asp-page="/Products/Delete" asp-route-id="@p.ProductId">Delete</a></td>
                    </tr>
                }
            </tbody>
        </table>
        <form method="post" asp-page-handler="paging">
            <div class="form-group m-2" hidden>
                <label for="categoryId">Filter</label>
                @foreach (var c in categories)
                {
                            <br/>
                                <input type="checkbox" name="category" value="@c.CategoryId" @(selectCate[categories.IndexOf(c)] ? "checked" : "")/>

                    @c.CategoryName
                }
            </div>
            <div class="form-group m-2" hidden>
                <label for="searchName">Search</label>
                <input type="text" name="searchName" placeholder="Product Name" value="@query"/><br/>
            </div>
            <div class="form-group m-2" hidden>
                <label for="searchName">Price</label>
                <input class="w-40" type="text" name="priceFrom" placeholder="From" value="@priceFrom" />
                <input class="w-40" type="text" name="priceTo" placeholder="To" value="@priceTo" />
            </div>
            <pager total-page='@((int)ViewData["TotalPage"])' active-class="active" 
                           url='/Products/List' current-page='@((int) ViewData["CurrentPage"])'>
            </pager>
        </form>
    </div>
</div>